install: true

language: php

dist: jammy

sudo: false

php:
  - 8.3
  - 8.4

before_script:
  - sudo apt-get update
  - sudo apt-get install subversion

script: echo "skip script"

deploy:
  provider: script
  cleanup: false
  script: chmod +x deploy.sh && sh deploy.sh
  on:
    branch: master
    php: 8.4
